package com.xworkz.interfaces.runner;

import com.xworkz.interfaces.extern.SavingAccount;
import com.xworkz.interfaces.intern.Account;
import com.xworkz.interfaces.extern.*;
import com.xworkz.interfaces.intern.*;

import javax.print.Doc;

public class Main {
    public static void main(String[] args) {
        Account account = new SavingAccount();
        account.closeAccount();
        SavingAccount savingAccount = new SavingAccount();
        savingAccount.checkBalance();
        savingAccount.closeAccount();
        savingAccount.deposit();
        savingAccount.printStatement();
        savingAccount.withdraw();
        System.out.println(Account.bankName);
        System.out.println(Account.accountNumber);
        System.out.println(Account.isActive);
        System.out.println(Account.balance);
        System.out.println(SavingAccount.contact);
        System.out.println("============================");
        Vehicle vehicle = new Car();
        vehicle.start();
        vehicle.changeGear();
        vehicle.brake();
        vehicle.addFuel();
        vehicle.stop();
        System.out.println(Vehicle.type);
        System.out.println(Vehicle.noOfWheels);
        System.out.println(Vehicle.isElectric);
        System.out.println(Vehicle.price);
        System.out.println(Vehicle.number);
        System.out.println("============================");
        Employee employee = new Manager();
        employee.attendMeeting();
        employee.work();
        employee.takeBreak();
        employee.report();
        employee.infom();
        System.out.println(Employee.empId);
        System.out.println(Employee.name);
        System.out.println(Employee.onDuty);
        System.out.println(Employee.phone);
        System.out.println(Employee.salary);
        System.out.println("============================");
        Person person=new Student();
        person.eat();
        person.work();
        person.study();
        person.talk();
        person.walk();
        System.out.println(Person.age);
        System.out.println(Person.aadharNumber);
        System.out.println(Person.name);
        System.out.println(Person.height);
        System.out.println(Person.isAdult);
        System.out.println("============================");
        Appliance appliance = new WashingMachine();
        appliance.startWash();
        appliance.rinse();
        appliance.spinDry();
        appliance.stopWash();
        appliance.showDetails();
        System.out.println(Appliance.brand);
        System.out.println(Appliance.capacity);
        System.out.println(Appliance.isAutomatic);
        System.out.println(Appliance.serial);
        System.out.println(Appliance.warrantyYears);
        System.out.println("============================");
        Computer computer = new Laptop();
        computer.boot();
        computer.open();
        computer.connectToWiFi();
        computer.close();
        computer.shutdown();
        System.out.println(Computer.brand);
        System.out.println(Computer.isAvaliable);
        System.out.println(Computer.ram);
        System.out.println(Computer.processorSpeed);
        System.out.println(Computer.serialNumber);
        System.out.println("============================");
        Media media = new Video();
        media.play();
        media.pause();
        media.stop();
        media.forward();
        media.replay();
        System.out.println(Media.mediaId);
        System.out.println(Media.duration);
        System.out.println(Media.name);
        System.out.println(Media.isHD);
        System.out.println(Media.size);
        System.out.println("============================");
        Document document = new PDF();
        document.compress();
        document.addPage();
        document.deletePage();
        document.highlightText();
        document.rename();
        System.out.println(Document.id);
        System.out.println(Document.name);
        System.out.println(Document.isPrintable);
        System.out.println(Document.num);
        System.out.println(Document.price);
        System.out.println("============================");
        Payment payment = new Creditcard();
        payment.pay();
        payment.cancel();
        payment.checkStatus();
        payment.showCardNumber();
        payment.showLimit();
        System.out.println(Payment.code);
        System.out.println(Payment.name);
        System.out.println(Payment.isActive);
        System.out.println(Payment.phoneNumber);
        System.out.println(Payment.pinNumber);
        System.out.println("==============================");
        Device device = new Smartphone();
        device.turnOn();
        device.reset();
        device.increaseVolume();
        device.turnOff();
        device.decreaseVolume();
        System.out.println(Device.brand);
        System.out.println(Device.isBranded);
        System.out.println(Device.number);
        System.out.println(Device.year);
        System.out.println(Device.price);
    }
}