package com.xworkz.interfaces.runner;
import com.xworkz.interfaces.implem.*;
import com.xworkz.interfaces.interfaces.*;
import jdk.management.resource.internal.inst.SocketRMHooks;

public class Runner {
    public static void main(String[] args) {
        App app=new Shopping();
        app.addToCart();
        app.checkout();
        app.searchProduct();
        Shopping shopping=new Shopping();
        shopping.addToCart();
        shopping.checkBattery();
        shopping.checkout();
        shopping.searchProduct();
        shopping.click();
        shopping.land();
        shopping.clearHistory();
        shopping.closeTab();
        shopping.off();
        shopping.openTab();
        shopping.powerOn();
        shopping.remoteControl();
        shopping.turnOn();
        shopping.takeOff();
        shopping.turnOff();
        System.out.println(Shopping.price);
        System.out.println(Shopping.hasRemote);
        System.out.println(Shopping.modelNumber);
        System.out.println(Shopping.maxSpeed);
        System.out.println(Shopping.modelName);
        System.out.println(Shopping.value);
        System.out.println(Shopping.isDigital);
        System.out.println(Shopping.brand);
        System.out.println(Shopping.pixels);
        System.out.println(Shopping.version);
        System.out.println(Shopping.isAvaliable);
        System.out.println(Shopping.names);
        System.out.println(Shopping.items);
        System.out.println(Shopping.isValid);
        System.out.println("===========================");
        Online online=new Online();
        online.startNavigation();
        online.startNavigation();
        online.searchLocation();
        online.play();
        online.tune();
        online.stop();
        online.turnOn();
        online.turnOff();
        online.connectDevice();
        online.trackSteps();
        online.monitorHeartRate();
        online.start();
        online.powerOn();
        online.changeChannel();
        online.increaseVolume();
        System.out.println(Online.language);
        System.out.println(Online.isOnline);
        System.out.println(Online.rating);
        System.out.println(Online.isPlaying);
        System.out.println(Online.weight);
        System.out.println(Online.instrumentId);
        System.out.println(Online.routerName);
        System.out.println(Online.speed);
        System.out.println(Online.serialNUmber);
        System.out.println(Online.total);
        System.out.println(Online.isValid);
        System.out.println(Online.brandName);
        System.out.println(Online.modelNumber);
        System.out.println(Online.brand);
        System.out.println(Online.size);
        System.out.println(Online.price);
    }
}
