package com.xworkz.abstractionn.runner;

import com.xworkz.abstractionn.main.*;
import com.xworkz.abstractionn.name.*;

public class Abstract {
    public static void main(String[] args) {
        ATM atm = new Bank();
        atm.insertCard();
        atm.enterPin();
        atm.selectTransaction();
        atm.processTransaction();
        atm.accountStatus();
        System.out.println("===========================================");
        Vehicle vehicle = new Car();
        vehicle.addFuel();
        vehicle.brake();
        vehicle.slowDown();
        vehicle.start();
        vehicle.stop();
        System.out.println("===========================================");
        Computer computer = new Laptop();
        computer.restart();
        computer.conntectInternet();
        computer.copyFile();
        computer.open();
        computer.shutdown();
        System.out.println("===========================================");
        Mobile mobile = new Vivo();
        mobile.installApp();
        mobile.makeCall();
        mobile.powerOff();
        mobile.sendMessage();
        mobile.powerOn();
        System.out.println("===========================================");
        Camera camera = new Niko();
        camera.click();
        camera.focus();
        camera.powerOff();
        camera.powerOn();
        camera.storeImage();
        System.out.println("===========================================");
        Music music = new Spotify();
        music.nextSong();
        music.pause();
        music.stop();
        music.play();
        music.previousSong();
        System.out.println("===========================================");
        Printer printer = new CanonPrinter();
        printer.powerOff();
        printer.powerOn();
        printer.printDocument();
        printer.scanDocument();
        printer.printPhoto();
        System.out.println("===========================================");
        Television television=new LGTv();
        television.powerOn();
        television.powerOff();
        television.changeChannel();
        television.decreaseVolume();
        television.increaseVolume();
        System.out.println("===========================================");
        Machine machine=new Nescafe();
        machine.brew();
        machine.start();
        machine.stop();
        machine.grindBeans();
        machine.serveCoffee();
        System.out.println("===========================================");
        SmartWatch smartWatch=new AppleWatch();
        smartWatch.trackSteps();
        smartWatch.call();
        smartWatch.measureHeartRate();
        smartWatch.powerOff();
        smartWatch.showTime();
        System.out.println("===========================================");
        Speaker speaker=new Alexa();
        speaker.answerQuestion();
        speaker.playMusic();
        speaker.stopMusic();
        speaker.shutDown();
        speaker.wakeWord();
        System.out.println("===========================================");
        Microwave microwave=new CromaL();
        microwave.off();
        microwave.powerOn();
        microwave.setTimer();
        microwave.startCooking();
        microwave.stopCooking();
        System.out.println("===========================================");
        AirConditioner airConditioner=new AC();
        airConditioner.activateMode();
        airConditioner.setTimer();
        airConditioner.setTemperature();
        airConditioner.turnOff();
        airConditioner.turnOn();
        System.out.println("===========================================");
        Browser browser=new Chrome();
        browser.bookmarkPage();
        browser.clearHistory();
        browser.closeTab();
        browser.refresh();
        browser.openTab();
        System.out.println("===========================================");
        Fan fan=new BajajFan();
        fan.decreaseSpeed();
        fan.turnOff();
        fan.turnOn();
        fan.increaseSpeed();
        fan.remoteControl();
        System.out.println("===========================================");
        Projector projector=new EpsonPj();
        projector.muteAudio();
        projector.connectHDMI();
        projector.powerOn();
        projector.powerOff();
        projector.displayContent();
        System.out.println("===========================================");
        Lamp lamp=new PhilipsLamp();
        lamp.brightness();
        lamp.dim();
        lamp.turnOff();
        lamp.turnOn();
        lamp.changeColor();
        System.out.println("===========================================");
        WashingMachine washingMachine=new WhirlpoopMc();
        washingMachine.startWash();
        washingMachine.rinse();
        washingMachine.turnOff();
        washingMachine.turnOn();
        washingMachine.speed();
        System.out.println("===========================================");
        Router router=new TPLRouter();
        router.connectDevice();
        router.disconnectDevice();
        router.turnOff();
        router.turnOn();
        router.showStatus();
        System.out.println("===========================================");
        Refrigerator refrigerator=new SamsungRef();
        refrigerator.cool();
        refrigerator.defrost();
        refrigerator.freeze();
        refrigerator.powerOff();
        refrigerator.setTemperature();
    }
}