package com.xworkz.abstractionn.runner;

import com.xworkz.abstractionn.main.*;
import com.xworkz.abstractionn.name.*;

public class Abstract {
    public static void main(String[] args) {
        ATM atm = new Bank();
        atm.insertCard();
        atm.enterPin();
        atm.selectTransaction();
        atm.processTransaction();
        atm.accountStatus();
        ATM.changePin();
        atm.dispReceipt();
        atm.depositCash();
        System.out.println("===========================================");
        Vehicle vehicle = new Car();
        vehicle.addFuel();
        vehicle.brake();
        vehicle.slowDown();
        vehicle.start();
        vehicle.stop();
        Vehicle.horn();
        vehicle.playMusic();
        vehicle.turnLight();
        System.out.println("===========================================");
        Computer computer = new Laptop();
        computer.restart();
        computer.conntectInternet();
        computer.copyFile();
        computer.open();
        computer.shutdown();
        Computer.updateSystem();
        computer.runProgram();
        computer.installApp();
        System.out.println("===========================================");
        Mobile mobile = new Vivo();
        mobile.installApp();
        mobile.makeCall();
        mobile.powerOff();
        mobile.sendMessage();
        mobile.powerOn();
        mobile.takePhoto();
        mobile.connectWifi();
        mobile.playMusic();
        System.out.println("===========================================");
        Camera camera = new Niko();
        camera.click();
        camera.focus();
        camera.powerOff();
        camera.powerOn();
        camera.storeImage();
        Camera.deleteImg();
        camera.zoom();
        camera.recordVideo();
        System.out.println("===========================================");
        Music music = new Spotify();
        music.nextSong();
        music.pause();
        music.stop();
        music.play();
        music.previousSong();
        music.shuffle();
        music.repeat();
        music.setVolume();
        System.out.println("===========================================");
        Printer printer = new CanonPrinter();
        printer.powerOff();
        printer.powerOn();
        printer.printDocument();
        printer.scanDocument();
        printer.printPhoto();
        printer.testPrint();
        printer.loadPaper();
        printer.connectWiFi();
        System.out.println("===========================================");
        Television television = new LGTv();
        television.powerOn();
        television.powerOff();
        television.changeChannel();
        television.decreaseVolume();
        television.increaseVolume();
        Television.muteVolume();
        television.connectWifi();
        television.subtitles();
        System.out.println("===========================================");
        Machine machine = new Nescafe();
        machine.brew();
        machine.start();
        machine.stop();
        machine.grindBeans();
        machine.serveCoffee();
        machine.cleanMachine();
        machine.addBeans();
        machine.addWater();
        System.out.println("===========================================");
        SmartWatch smartWatch = new AppleWatch();
        smartWatch.trackSteps();
        smartWatch.call();
        smartWatch.measureHeartRate();
        smartWatch.powerOff();
        smartWatch.showTime();
        SmartWatch.receiveNotification();
        smartWatch.coonectBluetooth();
        smartWatch.batteryStatus();
        System.out.println("===========================================");
        Speaker speaker = new Alexa();
        speaker.answerQuestion();
        speaker.playMusic();
        speaker.stopMusic();
        speaker.shutDown();
        speaker.wakeWord();
        Speaker.volumeIncrease();
        speaker.setAlarm();
        speaker.connectToWifi();
        System.out.println("===========================================");
        Microwave microwave = new CromaL();
        microwave.off();
        microwave.powerOn();
        microwave.setTimer();
        microwave.startCooking();
        microwave.stopCooking();
        microwave.openDoor();
        microwave.closeDoor();
        microwave.beepSound();
        System.out.println("===========================================");
        AirConditioner airConditioner = new AC();
        airConditioner.activateMode();
        airConditioner.setTimer();
        airConditioner.setTemperature();
        airConditioner.turnOff();
        airConditioner.turnOn();
        AirConditioner.checkstatus();
        airConditioner.incTemperature();
        airConditioner.showTemperature();
        System.out.println("===========================================");
        Browser browser = new Chrome();
        browser.bookmarkPage();
        browser.clearHistory();
        browser.closeTab();
        browser.refresh();
        browser.openTab();
        Browser.downloadFile();
        browser.goBack();
        browser.goForward();
        System.out.println("===========================================");
        Fan fan = new BajajFan();
        fan.decreaseSpeed();
        fan.turnOff();
        fan.turnOn();
        fan.increaseSpeed();
        fan.remoteControl();
        Fan.showingStatus();
        fan.clean();
        fan.connectApp();
        System.out.println("===========================================");
        Projector projector = new EpsonPj();
        projector.muteAudio();
        projector.connectHDMI();
        projector.powerOn();
        projector.powerOff();
        projector.displayContent();
        Projector.enableWiFi();
        projector.zoomIn();
        projector.zoomOut();
        System.out.println("===========================================");
        Lamp lamp = new PhilipsLamp();
        lamp.brightness();
        lamp.dim();
        lamp.turnOff();
        lamp.turnOn();
        lamp.changeColor();
        lamp.blink();
        lamp.showStatus();
        lamp.connectRemote();
        System.out.println("===========================================");
        WashingMachine washingMachine = new WhirlpoopMc();
        washingMachine.startWash();
        washingMachine.rinse();
        washingMachine.turnOff();
        washingMachine.turnOn();
        washingMachine.speed();
        WashingMachine.delayStart();
        washingMachine.addDetergent();
        washingMachine.spinDry();
        System.out.println("===========================================");
        Router router = new TPLRouter();
        router.connectDevice();
        router.disconnectDevice();
        router.turnOff();
        router.turnOn();
        router.showStatus();
        Router.changePassword();
        router.connecteddevices();
        router.restart();
        System.out.println("===========================================");
        Refrigerator refrigerator = new SamsungRef();
        refrigerator.cool();
        refrigerator.defrost();
        refrigerator.freeze();
        refrigerator.powerOff();
        refrigerator.setTemperature();
        Refrigerator.powerOn();
        refrigerator.filterCheck();
        refrigerator.givesInformation();
    }
}
