package com.xworkz.abstractionn.runner;

import com.xworkz.abstractionn.main.*;
import com.xworkz.abstractionn.name.*;
import com.xworkz.abstractionn.abstracts.*;
public class Abstract {
    public static void main(String[] args) {
        ATM atm = new Bank(3000);
        atm.insertCard();
        atm.enterPin();
        atm.selectTransaction();
        atm.processTransaction();
        atm.accountStatus();
        ATM.changePin();
        atm.dispReceipt();
        atm.depositCash();
        System.out.println("------static-------------");
        System.out.println(BankingDevice.isSecure);
        System.out.println("===========================================");
        Vehicle vehicle = new Car("Suzuki");
        vehicle.addFuel();
        vehicle.brake();
        vehicle.slowDown();
        vehicle.start();
        vehicle.stop();
        Vehicle.horn();
        vehicle.playMusic();
        vehicle.turnLight();
        System.out.println("------static-------------");
        System.out.println(Transportation.wheels);
        System.out.println("===========================================");
        Computer computer = new Laptop("HP");
        computer.restart();
        computer.conntectInternet();
        computer.copyFile();
        computer.open();
        computer.shutdown();
        Computer.updateSystem();
        computer.runProgram();
        computer.installApp();
        System.out.println("------static-------------");
        System.out.println(ElectronicDevice.speed);
        System.out.println("===========================================");
        Mobile mobile = new Vivo("Oneplus");
        mobile.installApp();
        mobile.makeCall();
        mobile.powerOff();
        mobile.sendMessage();
        mobile.powerOn();
        mobile.takePhoto();
        mobile.connectWifi();
        mobile.playMusic();
        System.out.println("------static-------------");
        System.out.println(Tablet.idNumber);
        System.out.println("===========================================");
        Camera camera = new Niko(10000);
        camera.click();
        camera.focus();
        camera.powerOff();
        camera.powerOn();
        camera.storeImage();
        Camera.deleteImg();
        camera.zoom();
        camera.recordVideo();
        System.out.println("------static-------------");
        System.out.println(Device.deviceGrade);
        System.out.println("===========================================");
        Music music = new Spotify(300);
        music.nextSong();
        music.pause();
        music.stop();
        music.play();
        music.previousSong();
        music.shuffle();
        music.repeat();
        music.setVolume();
        System.out.println("------static-------------");
        System.out.println(Media.duration);
        System.out.println("===========================================");
        Printer printer = new CanonPrinter('U');
        printer.powerOff();
        printer.powerOn();
        printer.printDocument();
        printer.scanDocument();
        printer.printPhoto();
        printer.testPrint();
        printer.loadPaper();
        printer.connectWiFi();
        System.out.println("------static-------------");
        System.out.println(Report.number);
        System.out.println("===========================================");
        Television television = new LGTv(25000);
        television.powerOn();
        television.powerOff();
        television.changeChannel();
        television.decreaseVolume();
        television.increaseVolume();
        Television.muteVolume();
        television.connectWifi();
        television.subtitles();
        System.out.println("------static-------------");
        System.out.println(PortableDevice.totalChannels);
        System.out.println("===========================================");
        Machine machine = new Nescafe(false);
        machine.brew();
        machine.start();
        machine.stop();
        machine.grindBeans();
        machine.serveCoffee();
        machine.cleanMachine();
        machine.addBeans();
        machine.addWater();
        System.out.println("------static-------------");
        System.out.println(MechanicalSystem.price);
        System.out.println("===========================================");
        SmartWatch smartWatch = new AppleWatch((short)65);
        smartWatch.trackSteps();
        smartWatch.call();
        smartWatch.measureHeartRate();
        smartWatch.powerOff();
        smartWatch.showTime();
        SmartWatch.receiveNotification();
        smartWatch.coonectBluetooth();
        smartWatch.batteryStatus();
        System.out.println("------static-------------");
        System.out.println(DigitalDevice.version);

        System.out.println("===========================================");
        Speaker speaker = new Alexa(true);
        speaker.answerQuestion();
        speaker.playMusic();
        speaker.stopMusic();
        speaker.shutDown();
        speaker.wakeWord();
        Speaker.volumeIncrease();
        speaker.setAlarm();
        speaker.connectToWifi();
        System.out.println("------static-------------");
        System.out.println(Audio.frequency);
        System.out.println("===========================================");
        Microwave microwave = new CromaL(567.54676);
        microwave.off();
        microwave.powerOn();
        microwave.setTimer();
        microwave.startCooking();
        microwave.stopCooking();
        microwave.openDoor();
        microwave.closeDoor();
        microwave.beepSound();
        System.out.println("------static-------------");
        System.out.println(Electronic.heatLevel);
        System.out.println("===========================================");
        AirConditioner airConditioner = new AC(false);
        airConditioner.activateMode();
        airConditioner.setTimer();
        airConditioner.setTemperature();
        airConditioner.turnOff();
        airConditioner.turnOn();
        AirConditioner.checkstatus();
        airConditioner.incTemperature();
        airConditioner.showTemperature();
        System.out.println("------static-------------");
        System.out.println(Appliance.brand);
        System.out.println("===========================================");
        Browser browser = new Chrome("Mozilla");
        browser.bookmarkPage();
        browser.clearHistory();
        browser.closeTab();
        browser.refresh();
        browser.openTab();
        Browser.downloadFile();
        browser.goBack();
        browser.goForward();
        System.out.println("------static-------------");
        System.out.println(Application.rating);
        System.out.println("===========================================");
        Fan fan = new BajajFan(45678989L);
        fan.decreaseSpeed();
        fan.turnOff();
        fan.turnOn();
        fan.increaseSpeed();
        fan.remoteControl();
        Fan.showingStatus();
        fan.clean();
        fan.connectApp();
        System.out.println("------static-------------");
        System.out.println(Gadgets.modes);
        System.out.println("===========================================");
        Projector projector = new EpsonPj(457689687);
        projector.muteAudio();
        projector.connectHDMI();
        projector.powerOn();
        projector.powerOff();
        projector.displayContent();
        Projector.enableWiFi();
        projector.zoomIn();
        projector.zoomOut();
        System.out.println("------static-------------");
        System.out.println(VisualProjection.category);
        System.out.println("===========================================");
        Lamp lamp = new PhilipsLamp("Electric lamp");
        lamp.brightness();
        lamp.dim();
        lamp.turnOff();
        lamp.turnOn();
        lamp.changeColor();
        lamp.blink();
        lamp.showStatus();
        lamp.connectRemote();
        System.out.println("------static-------------");
        System.out.println(LightSource.brightness);
        System.out.println("===========================================");
        WashingMachine washingMachine = new WhirlpoopMc(120);
        washingMachine.startWash();
        washingMachine.rinse();
        washingMachine.turnOff();
        washingMachine.turnOn();
        washingMachine.speed();
        WashingMachine.delayStart();
        washingMachine.addDetergent();
        washingMachine.spinDry();
        System.out.println("------static-------------");
        System.out.println(CleaningDevice.name);
        System.out.println("===========================================");
        Router router = new TPLRouter("TPL");
        router.connectDevice();
        router.disconnectDevice();
        router.turnOff();
        router.turnOn();
        router.showStatus();
        Router.changePassword();
        router.connecteddevices();
        router.restart();
        System.out.println("------static-------------");
        System.out.println(Network.bandwidth);
        System.out.println("===========================================");
        Refrigerator refrigerator = new SamsungRef('S');
        refrigerator.cool();
        refrigerator.defrost();
        refrigerator.freeze();
        refrigerator.powerOff();
        refrigerator.setTemperature();
        Refrigerator.powerOn();
        refrigerator.filterCheck();
        refrigerator.givesInformation();
        System.out.println("------static-------------");
        System.out.println(CoolingAppliance.serialNumber);
    }
}
