
package com.xworkz.objclass.runner;

import com.xworkz.objclass.internal.*;

public class Main {
    public static void main(String[] args) {
        Instrument ins = new Instrument();
        System.out.println(ins);
        Instrument instrument1 = new Instrument("Violin", (double)5000.0F, 120L, 4.5678988E7F, true);
        Instrument instrument = new Instrument("Violin", (double)5000.0F, 120L, 4.5678988E7F, true);
        System.out.println(instrument.toString());
        System.out.println(instrument1.equals(instrument));
        System.out.println(instrument.hashCode());
        System.out.println(instrument1.hashCode());
        System.out.println("========================");
        BankAccount ba = new BankAccount();
        System.out.println(ba);
        BankAccount bankAccount1 = new BankAccount("Ram", 3456789876L, (double)1000.0F, true, 'A');
        BankAccount bankAccount = new BankAccount("Ram", 3456789876L, (double)1000.0F, true, 'A');
        System.out.println(bankAccount);
        System.out.println(bankAccount.equals(bankAccount1));
        System.out.println(bankAccount.hashCode());
        System.out.println(bankAccount1.hashCode());
        System.out.println("========================");
        Movie movie = new Movie();
        System.out.println(movie);
        Movie movie2 = new Movie("Bhabubali", 2018, (double)9.0F, true, 'B');
        Movie movie1 = new Movie("Bhabubali", 2018, (double)9.0F, true, 'B');
        System.out.println(movie1);
        System.out.println(movie2.equals(movie1));
        System.out.println(movie2.hashCode());
        System.out.println(movie1.hashCode());
        System.out.println("========================");
        Ticket ticket = new Ticket();
        System.out.println(ticket);
        Ticket ticket2 = new Ticket("Nandu", 1234, 400.23, false, 'C');
        Ticket ticket1 = new Ticket("Nandu", 1234, 400.23, false, 'C');
        System.out.println(ticket1);
        System.out.println(ticket2.equals(ticket1));
        System.out.println(ticket2.hashCode());
        System.out.println(ticket1.hashCode());
        System.out.println("========================");
        Book book = new Book();
        System.out.println(book);
        Book book2 = new Book("The Names", 353.2, 250, 3.234F, true);
        Book book1 = new Book("The Names", 350.2, 250, 3.234F, true);
        System.out.println(book1);
        System.out.println(book1.equals(book2));
        System.out.println(book1.hashCode());
        System.out.println(book2.hashCode());
        System.out.println("========================");
        Laptop laptop = new Laptop();
        System.out.println(laptop);
        Laptop laptop2 = new Laptop("Hp", 'x', (double)242.0F, 128, 35465789L);
        Laptop laptop1 = new Laptop("Hp", 'x', (double)242.0F, 128, 35465789L);
        System.out.println(laptop1);
        System.out.println(laptop2.equals(laptop1));
        System.out.println(laptop2.hashCode());
        System.out.println(laptop1.hashCode());
        System.out.println("========================");
        Car car = new Car();
        System.out.println(car);
        Car car2 = new Car("Toyoto", 2017, (double)1993000.0F, 221L, true);
        Car car1 = new Car("Toyoto", 2017, (double)1993000.0F, 221L, true);
        System.out.println(car1);
        System.out.println(car1.equals(car2));
        System.out.println(car1.hashCode());
        System.out.println(car2.hashCode());
        System.out.println("========================");
        Student student = new Student();
        System.out.println(student);
        Student student2 = new Student("Krishna", 23, 76343545L, 'A', 8.3);
        Student student1 = new Student("Krishna", 23, 76343545L, 'A', 8.3);
        System.out.println(student1);
        System.out.println(student1.equals(student2));
        System.out.println(student1.hashCode());
        System.out.println(student2.hashCode());
        System.out.println("========================");
        House house = new House();
        System.out.println(house);
        House house2 = new House("srivaspur ,kolar", 6, (double)76500.0F, false, 244.53F);
        House house1 = new House("srivaspur ,kolar", 6, (double)76500.0F, false, 244.53F);
        System.out.println(house1);
        System.out.println(house1.equals(house2));
        System.out.println(house2.hashCode());
        System.out.println(house1.hashCode());
        System.out.println("========================");
        Phone phone = new Phone();
        System.out.println(phone);
        Phone phone2 = new Phone("OnePlus", 128, (double)35000.0F, true, 'S');
        Phone phone1 = new Phone("OnePlus", 128, (double)35000.0F, true, 'S');
        System.out.println(phone1);
        System.out.println(phone2.equals(phone1));
        System.out.println(phone2.hashCode());
        System.out.println(phone1.hashCode());
    }
}
